### ISSUE TITLE
Why the random seed looks quite strange?

### ISSUE THREAD

**Issue by DRJYYDS** [ivam-he/BernNet#1]
Did you treat the random seed as hyper-parameters? It's confusing to understand.

**Comment by ivam-he** [comment]
> Did you treat the random seed as hyper-parameters? It's confusing to understand.

These random seeds are not hyper-parameters and are used to generate dataset splits for all methods. We take these seeds from "https://github.com/gasteigerjo/gdc/blob/master/seeds.py," the random seeds used for dataset splits for GDC (https://arxiv.org/abs/1911.05485), a significant GNN work. We randomly used ten from the 100 seeds. You can also repeat the experiment with these 100 seeds, although this will take longer. I hope my answers will be helpful to you.

**Comment by DRJYYDS** [comment]
> > Did you treat the random seed as hyper-parameters? It's confusing to understand.
> 
> These random seeds are not hyper-parameters and are used to generate dataset splits for all methods. We take these seeds from "https://github.com/gasteigerjo/gdc/blob/master/seeds.py," the random seeds used for dataset splits for GDC (https://arxiv.org/abs/1911.05485), a significant GNN work. We randomly used ten from the 100 seeds. You can also repeat the experiment with these 100 seeds, although this will take longer. I hope my answers will be helpful to you.

Got it. Sorry for my misunderstanding at first. Thanks for your kind reply!
