### ISSUE TITLE
/home/BernNet-main/NodeClassification/dataset_loader.py文件中torch_sparse module出现问题

### ISSUE THREAD

**Issue by hhhhhh-925** [ivam-he/BernNet#3]
from torch_sparse import coalesce
ModuleNotFoundError: No module named 'torch_sparse'
当我运行training Chameleon Actor Squirrel三个数据集时有如上报错 尝试pip 和conda install torch_sparse均提示没有channel找不到torch_sparse请问有无解决办法

**Comment by ivam-he** [comment]
你可参考[torch_sparse](https://github.com/rusty1s/pytorch_sparse)安装torch_sparse，需要注意的是当前BernNet的代码是基于torch-geometric 1.6.3的，2.0以上的版本可能会报错。我后面尽可能更新代码到最新版本。
